#!/usr/bin/env node
// Generic "overlay mode" data builder — shared across Carbon sites.
// Unlike build.js (which generates a full HTML page per locale, used by
// SoulEntropy's homepage), overlay-mode sites keep ONE URL/locale baked in
// and let js/i18n.js (data-i18n-mode="overlay") swap text in the DOM at
// runtime. This script just assembles that runtime's data file from a
// site's own registry.json + strings.json — no page generation, no new
// hreflang claims (avoids the "thin duplicate SEO page" anti-pattern for
// sites whose long-form content isn't translated yet).
//
// Usage: node build-data.js <site-dir-containing-registry+strings.json> <dest-js-file>
// Example:
//   node build-data.js . ../js/i18n-data.js

const fs = require('fs');
const path = require('path');

const SITE_DIR = process.argv[2];
const DEST = process.argv[3];
if (!SITE_DIR || !DEST) {
  console.error('Usage: node build-data.js <site-dir> <dest-js-file>');
  process.exit(1);
}

const registry = JSON.parse(fs.readFileSync(path.join(SITE_DIR, 'registry.json'), 'utf8'));
const strings = JSON.parse(fs.readFileSync(path.join(SITE_DIR, 'strings.json'), 'utf8'));

const defaultLocale = registry.find((l) => l.default);
if (!defaultLocale) {
  console.error('registry.json must mark exactly one locale as "default": true');
  process.exit(1);
}

// Validate: every registry locale should have a strings entry (missing ones
// are allowed — they just fall back to en / default at runtime — but warn
// so gaps are visible and can feed the translation queue).
const missing = [];
for (const l of registry) {
  if (!strings[l.code]) {
    missing.push({ locale: l.code, key: '*' });
    continue;
  }
  const enKeys = Object.keys(strings[defaultLocale.code] || {});
  for (const key of enKeys) {
    if (!(key in strings[l.code])) missing.push({ locale: l.code, key });
  }
}

const payload = {
  registry,
  defaultLocale: defaultLocale.code,
  storageKey: path.basename(path.resolve(SITE_DIR, '..')) + '_lang',
  pageStrings: strings,
};

const out = `// AUTO-GENERATED by i18n-src/build-data.js — do not hand-edit. Edit strings.json instead.
window.__I18N__ = ${JSON.stringify(payload, null, 2)};
`;

fs.mkdirSync(path.dirname(DEST), { recursive: true });
fs.writeFileSync(DEST, out, 'utf8');
console.log(`Wrote ${DEST} (${registry.length} locales, default=${defaultLocale.code})`);
if (missing.length) {
  console.log(`Missing keys (${missing.length}) — see I18N_TRANSLATION_QUEUE.json for the queued list.`);
} else {
  console.log('No missing keys.');
}
